# Generated by Django 5.2.12 on 2026-04-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
